#!/bin/bash
# Function to retrieve DNS record information
function get_dns_info {
  local domain="$1"
  local subdomain="$2"
  local record_type="$3"
  dig +short "$subdomain.$domain" "$record_type" | awk '{printf "%s\n",$0}'
}

# Define domain and subdomains
domain="example.com"
subdomains=("www" "lb-01" "web-01" "web-02")

# If subdomain parameter is provided, only audit that subdomain
if [[ -n "$2" ]]; then
  subdomains=("$2")
fi

# Loop through subdomains and display DNS record information
for subdomain in "${subdomains[@]}"; do
  for record_type in "A" "CNAME"; do
    record_info=$(get_dns_info "$domain" "$subdomain" "$record_type")
    if [[ -n "$record_info" ]]; then
      echo "The subdomain $subdomain is a $record_type record and points to $record_info"
      break
    fi
  done
done

